# Generated by Django 4.2.30 on 2026-10-07 02:47
# Lưu ý: đã bổ sung `pgvector.django.VectorExtension()` ở đầu danh sách
# operations — BẮT BUỘC để tạo được cột `vector(768)` trên PostgreSQL.

import uuid

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models

import apps.rag.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Bật extension pgvector (idempotent).
        pgvector.django.VectorExtension(),
        # 2. Bảng tài liệu gốc.
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('summary', models.TextField(blank=True, default='')),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('root', models.TextField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to='rag_files/', validators=[apps.rag.validators.validate_document_extension, apps.rag.validators.validate_document_size])),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('done', 'Hoàn tất'), ('failed', 'Lỗi')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rag_rawdata',
                'ordering': ['-created_at'],
            },
        ),
        # 3. Bảng chunk + vector embedding.
        migrations.CreateModel(
            name='RagChunkData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_content', models.TextField()),
                ('chunk_index', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('vector', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('fts', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('raw_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.rawdata')),
            ],
            options={
                'db_table': 'rag_chunkdata',
                'ordering': ['raw_data', 'chunk_index'],
                'indexes': [
                    django.contrib.postgres.indexes.GinIndex(fields=['fts'], name='chunk_fts_gin_idx'),
                    django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='chunk_metadata_gin_idx'),
                    pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['vector'], m=16, name='chunk_vector_hnsw_idx', opclasses=['vector_cosine_ops']),
                ],
            },
        ),
    ]
