# Generated by Django on 2026-09-30

from django.db import migrations, models
import django.db.models.deletion
import django.contrib.postgres.search
import django.contrib.postgres.indexes
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        # Nhớ đổi tên migration phụ thuộc bên dưới cho đúng với dự án của bạn:
        # Ví dụ: ('rag', '0001_initial'),
        ('apps.rag', '0001_initial'),
    ]

    operations = [
        # 1. Đảm bảo Extension vector & btree_gin đã được bật trong Postgres
        pgvector.django.VectorExtension(),
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS btree_gin;",
            reverse_sql="DROP EXTENSION IF EXISTS btree_gin;"
        ),

        # 2. Tạo bảng RagData (rag_chunks)
        migrations.CreateModel(
            name='RagData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_data', models.TextField()),
                ('chunk_metadata', models.JSONField(blank=True, default=dict)),
                ('vector', pgvector.django.VectorField(blank=True, dimensions=1536, null=True)),
                ('fts_tokens', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                (
                    'raw_data',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='chunks',
                        to='rag.rawdata'  # Đổi 'rag.rawdata' thành 'ten_app.rawdata' nếu app đặt tên khác
                    )
                ),
            ],
            options={
                'db_table': 'rag_chunks',
            },
        ),

        # 3. Tạo các Index (HNSW cho Vector + GIN cho FTS & JSONB)
        migrations.AddIndex(
            model_name='ragdata',
            index=pgvector.django.HnswIndex(
                ef_construction=64,
                fields=['vector'],
                m=16,
                name='idx_ragdata_vector_hnsw',
                opclasses=['vector_cosine_ops'],
            ),
        ),
        migrations.AddIndex(
            model_name='ragdata',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['fts_tokens'],
                name='idx_ragdata_fts_gin'
            ),
        ),
        migrations.AddIndex(
            model_name='ragdata',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['chunk_metadata'],
                name='idx_ragdata_meta_gin'
            ),
        ),

        # 4. Tạo Trigger tự động cập nhật fts_tokens từ processed_data khi INSERT / UPDATE
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION update_ragdata_fts_tokens() RETURNS trigger AS $$
            begin
              new.fts_tokens := to_tsvector('simple', coalesce(new.processed_data, ''));
              return new;
            end
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS tsvectorupdate_ragdata ON rag_chunks;

            CREATE TRIGGER tsvectorupdate_ragdata
            BEFORE INSERT OR UPDATE ON rag_chunks
            FOR EACH ROW EXECUTE FUNCTION update_ragdata_fts_tokens();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS tsvectorupdate_ragdata ON rag_chunks;
            DROP FUNCTION IF EXISTS update_ragdata_fts_tokens();
            """
        ),
    ]