# Generated by Django 4.2.30 on 2026-10-07 02:47

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('message', apps.core.models.EncryptedJSONField(default=list)),
            ],
            options={
                'db_table': 'chat_chat',
                'ordering': ['-updated_at'],
            },
        ),
    ]
